# These are supported funding model platforms

github: [banxit]
patreon: [banxit]
open_collective: [banxit]
ko_fi: [banxit]
tidelift: [banxit]
community_bridge: [banxit]
liberapay: [banxit]
issuehunt: [banxit]
otechie: [banxit]
lfx_crowdfunding: [banxit]
custom: ['https://github.com/banxit/Valorant-Account-Checker']
